#!/usr/bin/env python3
"""
Auto-Skill Creation System — Inspired by Hermes Agent's procedural skill generation.
Analyzes completed complex tasks and generates SKILL.md files with:
- Step-by-step workflow
- Tools used
- Pitfalls encountered
- Success indicators

Triggered after multi-step task completion or invoked manually.
"""

import os
import json
from datetime import datetime
from pathlib import Path

WORKSPACE = Path(os.environ.get("OPENCLAW_WORKSPACE", "/home/wls/.openclaw/workspace-lisa"))
SKILLS_DIR = WORKSPACE / "skills"
MEMORY_DIR = WORKSPACE / "memory"

def generate_skill(
    name: str,
    description: str,
    steps: list,
    tools_used: list = None,
    pitfalls: list = None,
    success_indicators: list = None,
    category: str = "general",
    version: str = "1.0"
):
    """Generate a new skill directory with SKILL.md and manifest.json."""

    skill_dir = SKILLS_DIR / name.lower().replace(" ", "-")
    skill_dir.mkdir(parents=True, exist_ok=True)

    # Build SKILL.md
    steps_md = "\n".join(f"{i}. {s}" for i, s in enumerate(steps, 1))
    pitfalls_md = ""
    if pitfalls:
        pitfalls_md = "\n## Pitfalls\n\n" + "\n".join(f"- {p}" for p in pitfalls)

    tools_md = ""
    if tools_used:
        tools_md = "\n## Tools Used\n\n" + ", ".join(f"`{t}`" for t in tools_used)

    success_md = ""
    if success_indicators:
        success_md = "\n## Success Indicators\n\n" + "\n".join(f"- {s}" for s in success_indicators)

    skill_content = f"""---
name: {name}
description: {description}
category: {category}
version: {version}
created: {datetime.now().strftime("%Y-%m-%d")}
last_used: {datetime.now().strftime("%Y-%m-%d")}
---

# {name}

{description}

## Steps

{steps_md}
{tools_md}
{pitfalls_md}
{success_md}

## Notes

- Auto-generated by Lisa's skill creation system
- Update this skill when workflow changes are discovered
"""

    (skill_dir / "SKILL.md").write_text(skill_content)

    # Build manifest.json for quality tracking
    manifest = {
        "name": name,
        "version": version,
        "category": category,
        "created": datetime.now().isoformat(),
        "last_used": datetime.now().isoformat(),
        "use_count": 1,
        "success_count": 0,
        "failure_count": 0,
        "success_rate": None,
        "needs_revision": False,
        "tags": [category, "auto-generated"],
        "tools": tools_used or [],
        "source": "auto-generated"
    }

    (skill_dir / "manifest.json").write_text(json.dumps(manifest, indent=2))

    return str(skill_dir)


def update_skill_usage(skill_name: str, success: bool, notes: str = ""):
    """Update a skill's quality tracking after use."""
    skill_dir = SKILLS_DIR / skill_name.lower().replace(" ", "-")
    manifest_path = skill_dir / "manifest.json"

    if not manifest_path.exists():
        return False

    manifest = json.loads(manifest_path.read_text())
    manifest["use_count"] = manifest.get("use_count", 0) + 1
    manifest["last_used"] = datetime.now().isoformat()

    if success:
        manifest["success_count"] = manifest.get("success_count", 0) + 1
    else:
        manifest["failure_count"] = manifest.get("failure_count", 0) + 1
        if notes:
            manifest.setdefault("failure_notes", []).append({
                "date": datetime.now().isoformat(),
                "note": notes
            })

    total = manifest["success_count"] + manifest["failure_count"]
    if total > 0:
        manifest["success_rate"] = round(manifest["success_count"] / total * 100, 1)

    # Flag for revision if success rate drops below 50%
    if manifest["success_rate"] is not None and manifest["success_rate"] < 50 and total >= 3:
        manifest["needs_revision"] = True

    manifest_path.write_text(json.dumps(manifest, indent=2))
    return True


def list_skills_with_quality():
    """List all skills and their quality metrics."""
    skills = []
    if not SKILLS_DIR.exists():
        return skills

    for skill_dir in SKILLS_DIR.iterdir():
        if not skill_dir.is_dir():
            continue
        manifest_path = skill_dir / "manifest.json"
        if manifest_path.exists():
            manifest = json.loads(manifest_path.read_text())
            skills.append(manifest)
        else:
            # Legacy skill without manifest
            skill_md = skill_dir / "SKILL.md"
            if skill_md.exists():
                skills.append({
                    "name": skill_dir.name,
                    "use_count": 0,
                    "success_rate": None,
                    "needs_revision": True,  # No tracking = needs manifest
                    "source": "legacy"
                })
    return skills


if __name__ == "__main__":
    # Demo: list current skills with quality
    skills = list_skills_with_quality()
    if skills:
        print(f"📊 SKILL QUALITY TRACKER ({len(skills)} skills):")
        for s in skills:
            rate = f"{s['success_rate']}%" if s.get('success_rate') is not None else "N/A"
            revision = "⚠️ NEEDS REVISION" if s.get('needs_revision') else "✅ OK"
            print(f"  - {s['name']}: {s.get('use_count', 0)} uses, {rate} success, {revision}")
    else:
        print("No skills tracked yet.")