#!/usr/bin/env python3
# content_generator.py - Trending content creation

import subprocess
import json
import datetime
from typing import Dict

def generate_trending_content() -> Dict:
    """Generate content based on trending topics"""
    
    # Get trending topics from multiple platforms
    content_sources = {}
    
    # Reddit trends
    reddit_result = subprocess.run([
        'bb-browser', 'site', 'reddit/hot', 'cryptocurrency', '--json'
    ], capture_output=True, text=True)
    
    if reddit_result.returncode == 0:
        reddit_data = json.loads(reddit_result.stdout)
        content_sources['reddit'] = reddit_data.get('data', {}).get('posts', [])[:5]
    
    # Weibo trends
    weibo_result = subprocess.run([
        'bb-browser', 'site', 'weibo/hot', '--json'
    ], capture_output=True, text=True)
    
    if weibo_result.returncode == 0:
        weibo_data = json.loads(weibo_result.stdout)
        content_sources['weibo'] = weibo_data.get('data', {}).get('items', [])[:5]
    
    # Generate blog post
    blog_post = f"""
# Today's Crypto Market Insights - {datetime.datetime.now().strftime('%B %d, %Y')}

## Key Market Movements

Based on real-time social media analysis, here are the top cryptocurrency trends:

### Reddit Community Insights
"""
    
    for post in content_sources.get('reddit', []):
        blog_post += f"\n**{post.get('title', '')}**"
        blog_post += f"\n- Score: {post.get('score', 0)} | Comments: {post.get('num_comments', 0)}"
        blog_post += f"\n- Source: r/{post.get('subreddit', '')}"
        blog_post += "\n"
    
    blog_post += "\n### China Market Sentiment (Weibo)\n"
    
    for topic in content_sources.get('weibo', []):
        blog_post += f"\n**{topic.get('word', '')}**"
        blog_post += f"\n- Hot Value: {topic.get('hot_value', 0)} | Rank: {topic.get('rank', 0)}"
        blog_post += "\n"
    
    blog_post += f"""
## Market Analysis

The cryptocurrency market shows mixed signals today. Reddit sentiment indicates {len(content_sources.get('reddit', []))} major discussions, while Weibo trends show {len(content_sources.get('weibo', []))} hot topics.

## Investment Recommendations

1. **Monitor social sentiment** for early market signals
2. **Diversify portfolio** across different cryptocurrencies
3. **Stay informed** with real-time social media analysis

---
*Content generated by AI Market Intelligence System*
"""
    
    return {
        'blog_post': blog_post,
        'social_posts': [
            f"🚀 Crypto market update: {len(content_sources.get('reddit', []))} hot discussions on Reddit today!",
            f"🇨🇳 China crypto sentiment: {len(content_sources.get('weibo', []))} trending topics on Weibo",
            f"📊 Market intelligence: Real-time social sentiment analysis available"
        ],
        'timestamp': datetime.datetime.now().isoformat()
    }

if __name__ == "__main__":
    content = generate_trending_content()
    print("=== BLOG POST ===")
    print(content['blog_post'])
    print("\n=== SOCIAL POSTS ===")
    for post in content['social_posts']:
        print(f"- {post}")
    
    # Save content to files
    import os
    os.makedirs('/home/wls/content', exist_ok=True)
    
    # Save blog post
    blog_filename = f"/home/wls/content/blog_post_{datetime.datetime.now().strftime('%Y%m%d_%H%M')}.md"
    with open(blog_filename, 'w') as f:
        f.write(content['blog_post'])
    
    # Save social posts
    social_filename = f"/home/wls/content/social_posts_{datetime.datetime.now().strftime('%Y%m%d_%H%M')}.txt"
    with open(social_filename, 'w') as f:
        for post in content['social_posts']:
            f.write(f"{post}\n")
    
    print(f"\nContent saved:")
    print(f"Blog post: {blog_filename}")
    print(f"Social posts: {social_filename}")